# Generated by Django 5.2.6 on 2025-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractive',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
